version: '3'
services:
  spring_boot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "spring-boot-app"
    environment:
      - MONGO_HOST=mongodb
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"